### ISSUE TITLE
Investigate hdl backends from FuseSoC

### ISSUE THREAD

**Issue by mithro** [mithro/lxbe-tool#2]
I think @olofk had split the hdl backends from FuseSoC into a separate package? I can't find it now however?

**Comment by olofk** [comment]
I think you already found it by now, but for posterity the package is called edalize. It currently still lives in the FuseSoC repository but as a separate python package. Will move it out once there is some documentation or users who need it stand-alone

**Comment by mithro** [comment]
@olofk also said in an email to me when asking if edalize made sense for this usage;

> Edalize would be quite useless for that :) 
>
> The main reason is that edalize works in three stages. First, configure, which creates all the project files and a Makefile, then build, which basically calls the makefile to build the bitstream/simulation model and finally it can optionally run the created artifact
>
> This means that edalize has no idea if the tools exists until it tries to execute them during build or run. 


We really want to detect what tools are available and make sure they work correctly which is not what edalize is for.
